### USA CARS DATA Pre-processing

In [2]:
#Read the data into a dataframe
import pandas as pd
df = pd.read_csv("USA_cars_datasets.csv")

In [3]:
#Preview of the dataset
df.head(10)

,Unnamed: 0,price($),brand,model,year,title_status,mileage,color,vin,lot,state,country,condition
0,0,6300,toyota,cruiser,2008,clean vehicle,274117,black,jtezu11f88k007763,159348797,new jersey,usa,10 days left
1,1,2899,ford,se,2011,clean vehicle,190552,silver,2fmdk3gc4bbb02217,166951262,tennessee,usa,6 days left
2,2,5350,dodge,mpv,2018,clean vehicle,39590,silver,3c4pdcgg5jt346413,167655728,georgia,usa,2 days left
3,3,25000,ford,door,2014,clean vehicle,64146,blue,1ftfw1et4efc23745,167753855,virginia,usa,22 hours left
4,4,27700,chevrolet,1500,2018,clean vehicle,6654,red,3gcpcrec2jg473991,167763266,florida,usa,22 hours left
5,5,5700,dodge,mpv,2018,clean vehicle,45561,white,2c4rdgeg9jr237989,167655771,texas,usa,2 days left
6,6,7300,chevrolet,pk,2010,clean vehicle,149050,black,1gcsksea1az121133,167753872,georgia,usa,22 hours left
7,7,13350,gmc,door,2017,clean vehicle,23525,gray,1gks2gkc3hr326762,167692494,california,usa,20 hours left
8,8,14600,chevrolet,malibu,2018,clean vehicle,9371,silver,1g1zd5st5jf191860,167763267,florida,usa,22 hours left
9,9,5250,ford,mpv,2017,clean vehicle,63418,black,2fmpk3j92hbc12542,167656121,texas,usa,2 days left

In [4]:
#Sumamry of the dataset
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2499 entries, 0 to 2498
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Unnamed: 0    2499 non-null   int64
 1   price($)      2499 non-null   int64
 2   brand         2499 non-null   object
 3   model         2499 non-null   object
 4   year          2499 non-null   int64
 5   title_status  2499 non-null   object
 6   mileage       2499 non-null   int64
 7   color         2499 non-null   object
 8   vin           2499 non-null   object
 9   lot           2499 non-null   int64
 10  state         2499 non-null   object
 11  country       2499 non-null   object
 12  condition     2499 non-null   object
dtypes: int64(5), object(8)
memory usage: 253.9+ KB

In [5]:
#Statistical summary of the dataset
df.describe()

        Unnamed: 0      price($)         year       mileage           lot
count  2499.000000   2499.000000  2499.000000  2.499000e+03  2.499000e+03
mean   1249.000000  18767.671469  2016.714286  5.229869e+04  1.676914e+08
std     721.543484  12116.094936     3.442656  5.970552e+04  2.038772e+05
min       0.000000      0.000000  1973.000000  0.000000e+00  1.593488e+08
25%     624.500000  10200.000000  2016.000000  2.146650e+04  1.676253e+08
50%    1249.000000  16900.000000  2018.000000  3.536500e+04  1.677451e+08
75%    1873.500000  25555.500000  2019.000000  6.347250e+04  1.677798e+08
max    2498.000000  84900.000000  2020.000000  1.017936e+06  1.678055e+08

In [6]:
#Check for missing values
df.isnull().sum()

Unnamed: 0      0
price($)        0
brand           0
model           0
year            0
title_status    0
mileage         0
color           0
vin             0
lot             0
state           0
country         0
condition       0
dtype: int64

### Catgorical Columns

In [7]:
#Dropping the unnecesasry column
df = df.drop('Unnamed: 0', axis=1)

In [ ]:
#Number of unique values in each categorical column
#This will help us understand the categorical columns better
categorical_cols = df.select_dtypes(include=['object'])
unique_value_counts = categorical_cols.nunique()
print(unique_value_counts)

brand             28
model            127
title_status       2
color             49
vin             2495
state             44
country            2
condition         47
dtype: int64

In [9]:
#Count of unique values in each categorical column
unique_counts = {col: df[col].value_counts().to_dict() for col in categorical_cols}

for col, values in unique_counts.items():
    print(f"{col}: {values}")

brand: {'ford': 1235, 'dodge': 432, 'nissan': 312, 'chevrolet': 297, 'gmc': 42, 'jeep': 30, 'chrysler': 18, 'bmw': 17, 'hyundai': 15, 'kia': 13, 'buick': 13, 'infiniti': 12, 'honda': 12, 'cadillac': 10, 'mercedes-benz': 10, 'heartland': 5, 'land': 4, 'peterbilt': 4, 'audi': 4, 'acura': 3, 'lincoln': 2, 'lexus': 2, 'mazda': 2, 'maserati': 1, 'toyota': 1, 'harley-davidson': 1, 'jaguar': 1, 'ram': 1}
model: {'door': 651, 'f-150': 219, 'doors': 148, 'caravan': 102, 'mpv': 87, 'fusion': 65, 'durango': 64, 'journey': 61, 'rogue': 54, 'van': 46, 'challenger': 44, 'charger': 42, 'max': 41, 'transit': 41, 'sport': 40, '1500': 39, 'explorer': 39, 'escape': 39, 'srw': 38, 'edge': 34, 'versa': 34, 'flex': 33, 'wagon': 30, 'mustang': 29, 'sentra': 28, 'expedition': 28, 'pathfinder': 22, 'altima': 21, 'equinox': 18, 'suburban': 16, 'pickup': 15, 'fiesta': 14, 'frontier': 14, 'colorado': 12, 'impala': 12, 'cutaway': 12, 'malibu': 12, 'drw': 10, 'taurus': 10, 'tahoe': 9, 'focus': 9, '2500': 8, 'series': 8, 'trax': 8, 'cab': 8, 'ecosport': 7, 'traverse': 6, 'coupe': 6, '300': 6, 'compass': 6, 'ranger': 6, 'camaro': 6, 'sorento': 5, 'titan': 5, 'hybrid': 5, 'pk': 5, 'murano': 5, 'sedan': 4, 'truck': 4, 'chassis': 4, 'armada': 4, '3500': 4, 'corvette': 4, 'f-650': 3, 'passenger': 3, 'ld': 3, 'maxima': 3, 'encore': 3, 'el': 3, 'cherokee': 3, 'pacifica': 3, 'bus': 2, 'cruze': 2, 'forte': 2, 'volt': 2, 'vans': 2, 'enclave': 2, 'sonic': 2, 'country': 2, 'x3': 2, 'd': 2, 'cargo': 2, 'note': 2, 'gle': 2, 'xterra': 1, 'energi': 1, 'juke': 1, 'f-750': 1, 'dr': 1, 'suv': 1, 'kicks': 1, 'xd': 1, 'connect': 1, 'cruiser': 1, 'sundance': 1, 'spark': 1, 'xt5': 1, 'q70': 1, 'convertible': 1, 'm': 1, 'dart': 1, 'esv': 1, 'srx': 1, 'vehicl': 1, 'soul': 1, 'elantra': 1, 'pioneer': 1, 'trail': 1, 'se': 1, 'road/street': 1, 'nautilus': 1, 'gx': 1, 'q5': 1, 'sportage': 1, '5': 1, 'discovery': 1, 'acadia': 1, 'ghibli': 1, 'glc': 1, 'e-class': 1, 'utility': 1, 'limited': 1, 'sl-class': 1, 'cx-3': 1, '2500hd': 1, 'mdx': 1, 'nvp': 1}
title_status: {'clean vehicle': 2336, 'salvage insurance': 163}
color: {'white': 707, 'black': 516, 'gray': 395, 'silver': 300, 'red': 192, 'blue': 151, 'no_color': 61, 'green': 24, 'orange': 20, 'gold': 19, 'charcoal': 18, 'brown': 15, 'yellow': 9, 'magnetic metallic': 6, 'shadow black': 5, 'color:': 5, 'beige': 5, 'oxford white': 4, 'ingot silver metallic': 4, 'super black': 3, 'billet silver metallic clearcoat': 3, 'triple yellow tri-coat': 3, 'cayenne red': 2, 'white platinum tri-coat metallic': 2, 'off-white': 2, 'ruby red metallic tinted clearcoat': 2, 'tuxedo black metallic': 2, 'black clearcoat': 2, 'bright white clearcoat': 2, 'morningsky blue': 1, 'guard': 1, 'pearl white': 1, 'tan': 1, 'burgundy': 1, 'ingot silver': 1, 'lightning blue': 1, 'jazz blue pearlcoat': 1, 'kona blue metallic': 1, 'royal crimson metallic tinted clearcoat': 1, 'ruby red': 1, 'competition orange': 1, 'purple': 1, 'toreador red': 1, 'light blue': 1, 'phantom black': 1, 'maroon': 1, 'dark blue': 1, 'turquoise': 1, 'glacier white': 1}

### Check for duplicate VIN numbers, VIN is a unique 17-character alphanumeric code assigned to every vehicle.

In [10]:
#Checking for VIN duplicates in the dataset, which should be unique for each car   
repeated_vins = df['vin'].value_counts()
repeated_vins = repeated_vins[repeated_vins > 1].index
print(repeated_vins)

Index(['  1gnevhkw8jj148388', '  1gndt13s632267445', '  3gcrkse37ag234620',
       '  1g1al58f787159241'],
      dtype='object', name='vin')

In [11]:
#Preview of the dataset with repeated VINs
repeated_vin_rows = df[df['vin'].isin(repeated_vins)]
print(repeated_vin_rows)

     price($)      brand     model  year       title_status  mileage  color  \
301        50  chevrolet      door  2008  salvage insurance   172102   blue
310         0  chevrolet      door  2003  salvage insurance   194673   gray
319        25  chevrolet    pickup  2010  salvage insurance   149189  white
336     26900  chevrolet  traverse  2018      clean vehicle    42941  black
518        50  chevrolet      door  2008  salvage insurance   172102   blue
530         0  chevrolet      door  2003  salvage insurance   194673   gray
541        25  chevrolet    pickup  2010  salvage insurance   149189  white
661     26900  chevrolet  traverse  2018      clean vehicle    42941  black

                     vin        lot     state country      condition
301    1g1al58f787159241  167650632     texas     usa  18 hours left
310    1gndt13s632267445  167650636     texas     usa  18 hours left
319    3gcrkse37ag234620  167650663  colorado     usa  18 hours left
336    1gnevhkw8jj148388  167781794  missouri     usa  20 hours left
518    1g1al58f787159241  167650632     texas     usa  17 hours left
530    1gndt13s632267445  167650636     texas     usa  17 hours left
541    3gcrkse37ag234620  167650663  colorado     usa  17 hours left
661    1gnevhkw8jj148388  167781794  missouri     usa  19 hours left

### Baed on the condition I dropped the duplicated VIN rows

In [12]:
#Dropping the rows with repeated VINs
#This is a sample of the rows to be dropped, you can choose to drop all or some of them based on your analysis
rows_to_drop = [518,530,661,541]
df = df.drop(rows_to_drop)

In [ ]:
#Check the length of VINs in the dataset
#This will help us understand if there are any invalid VINs in the dataset
print(df['vin'].dropna().str.len().unique())

[19 15]

In [36]:
df = df[df['vin'].str.len() == 19]      # Keep only 17-character VINs

In [13]:
#Summary of the dataset after a little preprocessing
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2495 entries, 0 to 2498
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   price($)      2495 non-null   int64
 1   brand         2495 non-null   object
 2   model         2495 non-null   object
 3   year          2495 non-null   int64
 4   title_status  2495 non-null   object
 5   mileage       2495 non-null   int64
 6   color         2495 non-null   object
 7   vin           2495 non-null   object
 8   lot           2495 non-null   int64
 9   state         2495 non-null   object
 10  country       2495 non-null   object
 11  condition     2495 non-null   object
dtypes: int64(4), object(8)
memory usage: 253.4+ KB

In [14]:
#Confirming there are no duplicates in the lot column
distinct_lot_count = df['lot'].nunique()
print(f"Number of distinct values in 'lot': {distinct_lot_count}")

Number of distinct values in 'lot': 2495

### Lets Preprocess the brands and models column

In [16]:
#Unique models in the dataset
models = df['model'].unique()
models

array(['cruiser', 'se', 'mpv', 'door', '1500', 'pk', 'malibu', 'coupe',
       'wagon', 'forte', 'encore', 'sorento', 'doors', 'chassis', 'q70',
       'camaro', 'convertible', 'vans', 'srw', 'compass', 'enclave',
       '300', 'cherokee', 'pacifica', 'x3', 'equinox', 'challenger', 'm',
       'colorado', 'focus', 'durango', 'escape', 'charger', 'explorer',
       'f-150', '3500', 'caravan', 'van', 'dart', '2500', 'esv',
       'cutaway', 'el', 'edge', 'series', 'flex', 'srx', 'cab', 'pickup',
       'vehicl', 'trax', 'tahoe', 'suburban', 'cargo', 'drw', 'fiesta',
       'impala', 'soul', 'elantra', 'pioneer', 'trail', 'traverse',
       'country', 'sundance', 'road/street', 'nautilus', 'gx', 'q5',
       'gle', 'sportage', '5', 'sport', 'discovery', 'acadia', 'ghibli',
       'glc', 'e-class', 'truck', 'utility', 'limited', 'sl-class',
       'cx-3', '2500hd', 'sonic', 'corvette', 'mdx', 'xt5', 'fusion',
       'mustang', 'passenger', 'volt', 'spark', 'cruze', 'ld', 'journey',
       'transit', 'ranger', 'taurus', 'max', 'energi', 'expedition',
       'bus', 'ecosport', 'f-750', 'd', 'dr', 'hybrid', 'suv', 'connect',
       'f-650', 'sentra', 'altima', 'frontier', 'rogue', 'maxima',
       'versa', 'note', 'armada', 'pathfinder', 'titan', 'sedan', 'juke',
       'murano', 'xterra', 'kicks', 'xd', 'nvp'], dtype=object)

In [ ]:
#Function to clean model names
#This function will replace common abbreviations and typos in the model names with their full forms
def clean_model_names(df, column='model'):
    replacements = {
        'vehicl': 'vehicle',
        'pk': 'pickup',
        'dr': 'door',
        'drw': 'dual rear wheel',
        'srw': 'single rear wheel',
        'ld': 'limited',
        'd': 'drive',
        'door': 'doors',  #unify
        'el': 'EL',
        'trail': 'Trailblazer',  #or Trail
        'country': 'Town & Country',
        'max': 'C-Max',
        'note': 'Note',  #assuming Nissan Note
        'pioneer': 'Pioneer',  #assuming valid model
        'sundance': 'Sundance',
        'energi': 'Energi',
    }
    df[column] = df[column].str.lower()
    df[column] = df[column].replace(replacements)
    return df

In [18]:
df = clean_model_names(df, column='model')

In [22]:
#Uppercasing the brands and model naems that are 3 characters or less
#This is a common practice to standardize the data and make it easier to analyze
df.loc[:, 'brand'] = df['brand'].apply(lambda x: x.upper() if isinstance(x, str) and len(x) <= 3 else x)
df.loc[:, 'model'] = df['model'].apply(lambda x: x.upper() if isinstance(x, str) and len(x) <= 3 else x)

In [21]:
df['model'].unique()

array(['cruiser', 'SE', 'MPV', 'doors', '1500', 'pickup', 'malibu',
       'coupe', 'wagon', 'forte', 'encore', 'sorento', 'chassis', 'Q70',
       'camaro', 'convertible', 'vans', 'single rear wheel', 'compass',
       'enclave', '300', 'cherokee', 'pacifica', 'X3', 'equinox',
       'challenger', 'M', 'colorado', 'focus', 'durango', 'escape',
       'charger', 'explorer', 'f-150', '3500', 'caravan', 'VAN', 'dart',
       '2500', 'ESV', 'cutaway', 'EL', 'edge', 'series', 'flex', 'SRX',
       'CAB', 'vehicle', 'trax', 'tahoe', 'suburban', 'cargo',
       'dual rear wheel', 'fiesta', 'impala', 'soul', 'elantra',
       'Pioneer', 'Trailblazer', 'traverse', 'Town & Country', 'Sundance',
       'road/street', 'nautilus', 'GX', 'Q5', 'GLE', 'sportage', '5',
       'sport', 'discovery', 'acadia', 'ghibli', 'GLC', 'e-class',
       'truck', 'utility', 'limited', 'sl-class', 'cx-3', '2500hd',
       'sonic', 'corvette', 'MDX', 'XT5', 'fusion', 'mustang',
       'passenger', 'volt', 'spark', 'cruze', 'journey', 'transit',
       'ranger', 'taurus', 'C-Max', 'Energi', 'expedition', 'BUS',
       'ecosport', 'f-750', 'drive', 'door', 'hybrid', 'SUV', 'connect',
       'f-650', 'sentra', 'altima', 'frontier', 'rogue', 'maxima',
       'versa', 'Note', 'armada', 'pathfinder', 'titan', 'sedan', 'juke',
       'murano', 'xterra', 'kicks', 'XD', 'NVP'], dtype=object)

In [23]:
#Applying title case to all string columns
df = df.apply(lambda col: col.str.title() if col.dtype == 'object' else col)
df['country'] = df['country'].str.upper()

In [24]:
#Descriptive statistics of the dataset
#This will give us a summary of the dataset including count, mean, std, min, 25%, 50%, 75%, max for numerical columns
df.describe(include='all')

,price($),brand,model,year,title_status,mileage,color,vin,lot,state,country,condition
count,2495.000000,2495,2495,2495.000000,2495,2.495000e+03,2495,2495,2.495000e+03,2495,2495,2495
unique,NaN,28,124,NaN,2,NaN,49,2495,NaN,44,2,47
top,NaN,Ford,Doors,NaN,Clean Vehicle,NaN,White,Jtezu11F88K007763,NaN,Pennsylvania,USA,2 Days Left
freq,NaN,1235,797,NaN,2335,NaN,706,1,NaN,299,2488,832
mean,18786.948297,NaN,NaN,2016.725451,NaN,5.215852e+04,NaN,NaN,1.676914e+08,NaN,NaN,NaN
std,12107.260299,NaN,NaN,3.427268,NaN,5.960507e+04,NaN,NaN,2.040277e+05,NaN,NaN,NaN
min,0.000000,NaN,NaN,1973.000000,NaN,0.000000e+00,NaN,NaN,1.593488e+08,NaN,NaN,NaN
25%,10297.500000,NaN,NaN,2016.000000,NaN,2.140550e+04,NaN,NaN,1.676253e+08,NaN,NaN,NaN
50%,16900.000000,NaN,NaN,2018.000000,NaN,3.532600e+04,NaN,NaN,1.677451e+08,NaN,NaN,NaN
75%,25555.500000,NaN,NaN,2019.000000,NaN,6.335450e+04,NaN,NaN,1.677798e+08,NaN,NaN,NaN
max,84900.000000,NaN,NaN,2020.000000,NaN,1.017936e+06,NaN,NaN,1.678055e+08,NaN,NaN,NaN

### Lets analyze the rows that have 0 price($)

In [25]:
zero_price_df = df[df['price($)'] == 0]
zero_price_df

,price($),brand,model,year,title_status,mileage,color,vin,lot,state,country,condition
141,0,Dodge,Van,2008,Salvage Insurance,177948,Orange,2D8Hn44H88R669549,167756157,Utah,USA,2 Days Left
144,0,Dodge,Doors,2014,Salvage Insurance,123660,Silver,1C3Cdzab0En111068,167756167,Utah,USA,2 Days Left
196,0,Ford,Mpv,2017,Clean Vehicle,76858,White,1Fbax2Cv0Hkb32599,167656523,Texas,USA,2 Days Left
285,0,Ford,Doors,2000,Salvage Insurance,124969,Black,1Fafp34P7Yw270338,167251902,Oklahoma,USA,17 Hours Left
290,0,Mazda,Doors,2009,Salvage Insurance,117541,Gray,Jm3Er293590215768,167543177,Indiana,USA,16 Hours Left
293,0,Chevrolet,Pickup,1998,Salvage Insurance,258631,Gray,1Gccs1445Wk226994,167417659,Texas,USA,17 Hours Left
297,0,Honda,Doors,2003,Salvage Insurance,152608,White,1Hgcm56363A030975,167552893,Arkansas,USA,17 Hours Left
305,0,Ford,Doors,2003,Salvage Insurance,246065,Gold,1Fafp55U03A242094,167610324,Kansas,USA,8 Days Left
309,0,Chevrolet,Doors,2004,Salvage Insurance,0,Maroon,3Gnek12T74G240524,167418651,Wyoming,USA,18 Hours Left
310,0,Chevrolet,Doors,2003,Salvage Insurance,194673,Gray,1Gndt13S632267445,167650636,Texas,USA,18 Hours Left
313,0,Ford,Van,1998,Salvage Insurance,186855,Blue,2Fmda5143Wba16791,167359170,California,USA,19 Hours Left
314,0,Ford,Doors,2013,Salvage Insurance,94004,Black,3Fa6P0H74Dr270819,167610728,Minnesota,USA,17 Hours Left
318,0,Chevrolet,Doors,2009,Salvage Insurance,117059,Black,Kl1Td66E39B645208,167418694,Colorado,USA,18 Hours Left
322,0,Ford,Chassis,1994,Salvage Insurance,0,Green,1Fdee14N7Rha47894,167359174,California,USA,19 Hours Left
323,0,Ford,Doors,1997,Salvage Insurance,203297,Green,1Fmdu35P7Vub38059,167610731,Minnesota,USA,17 Hours Left
330,0,Ford,Doors,1996,Salvage Insurance,296860,Green,1Falp62W5Th144314,167359712,California,USA,19 Hours Left
331,0,Ford,Doors,2006,Salvage Insurance,203158,Red,1Fmzk04136Ga07119,167610991,Illinois,USA,17 Hours Left
339,0,Ford,Doors,2002,Salvage Insurance,214800,Black,3Fafp37372R151014,167360232,South Carolina,USA,2 Days Left
344,0,Chevrolet,Doors,2010,Salvage Insurance,137422,Red,2Cnflnew5A6355858,167650683,Colorado,USA,18 Hours Left
347,0,Gmc,Doors,2004,Salvage Insurance,235348,Gold,1Gket16S646227597,167360322,South Carolina,USA,2 Days Left
349,0,Heartland,Sundance,2009,Clean Vehicle,1,White,5Sfgf29269E031344,167266321,Pennsylvania,USA,7 Days Left
351,0,Chevrolet,Doors,2008,Salvage Insurance,159266,Gray,2G1Wb58Kx81220813,167650796,California,USA,19 Hours Left
354,0,Ford,Pickup,2009,Salvage Insurance,180364,Blue,1Ftyr10D19Pa60391,167360535,Tennessee,USA,2 Days Left
355,0,Ford,Doors,2009,Salvage Insurance,184889,Black,1Fahp35N09W109143,167611047,Illinois,USA,17 Hours Left
370,0,Ford,Doors,1997,Salvage Insurance,146912,Green,1Ftdf18W8Vna61251,167362449,Wisconsin,USA,2 Days Left
371,0,Ford,Doors,1998,Salvage Insurance,131367,White,1Ftrf18L7Wka62471,167611301,Illinois,USA,17 Hours Left
391,0,Cadillac,Coupe,2000,Salvage Insurance,105169,White,1G6El12Y9Yu148063,167651218,Virginia,USA,9 Days Left
400,0,Buick,Doors,2006,Salvage Insurance,137464,Blue,2G4Wc582961163677,167651221,Virginia,USA,9 Days Left
410,0,Chevrolet,Doors,1995,Salvage Insurance,274706,Green,2Gcec19H8S1195266,167425634,Arizona,USA,2 Days Left
419,0,Kia,Wagon,2008,Salvage Insurance,148463,Silver,Knafg525787197602,167247592,Indiana,USA,16 Hours Left
420,0,Audi,Doors,2005,Salvage Insurance,181896,Black,Waudg74F05N113751,167419563,California,USA,19 Hours Left
421,0,Bmw,Doors,2000,Salvage Insurance,216657,Gray,Wbaam3346Yfp77118,167425906,Utah,USA,2 Days Left
435,0,Ford,Doors,2004,Salvage Insurance,167011,Red,1Fmfu18L84Lb61201,167601555,Maryland,USA,16 Hours Left
443,0,Chevrolet,Coupe,2008,Salvage Insurance,270080,Yellow,1G1Al18F187245041,167650422,Illinois,USA,17 Hours Left
455,0,Chevrolet,Doors,2006,Salvage Insurance,268040,Silver,1G1Zt53F46F254868,167650486,Texas,USA,17 Hours Left
496,0,Ford,Pickup,1996,Salvage Insurance,252588,Red,1Ftef15N0Tlc14455,167357804,Oklahoma,USA,17 Hours Left
506,0,Chevrolet,Doors,2012,Salvage Insurance,134938,Orange,1G1Jc5Sh7C4114661,167650604,Oklahoma,USA,17 Hours Left
510,0,Ford,Doors,2010,Salvage Insurance,86841,Silver,3Fahp0Ga3Ar366961,167357806,Oklahoma,USA,17 Hours Left
514,0,Lincoln,Doors,2005,Salvage Insurance,89705,Green,1Lnhm87A25Y619997,167154617,Minnesota,USA,17 Hours Left
516,0,Peterbilt,Truck,2009,Salvage Insurance,982486,Blue,1Xp7D49X09D784257,167529788,Florida,USA,17 Hours Left
522,0,Ford,Doors,2008,Salvage Insurance,145483,Red,1Fmcu03128Kc80487,167357813,Oklahoma,USA,17 Hours Left
545,0,Gmc,Doors,1993,Salvage Insurance,0,Light Blue,1Gkfk16K5Pj701631,167358601,Colorado,USA,18 Hours Left

In [26]:
#Considering it is a auctions car dataset, we can assume that the mileage of a car cannot be 0,1 or other.
#So we considered the cars with at least 10 miles as valid cars.
df = df[df['mileage'] >= 10]

### Now, lets preprocess the condition column

In [27]:
#renaming the column name to time_left
df.rename(columns={'condition': 'time_left'})

,price($),brand,model,year,title_status,mileage,color,vin,lot,state,country,time_left
0,6300,Toyota,Cruiser,2008,Clean Vehicle,274117,Black,Jtezu11F88K007763,159348797,New Jersey,USA,10 Days Left
1,2899,Ford,Se,2011,Clean Vehicle,190552,Silver,2Fmdk3Gc4Bbb02217,166951262,Tennessee,USA,6 Days Left
2,5350,Dodge,Mpv,2018,Clean Vehicle,39590,Silver,3C4Pdcgg5Jt346413,167655728,Georgia,USA,2 Days Left
3,25000,Ford,Doors,2014,Clean Vehicle,64146,Blue,1Ftfw1Et4Efc23745,167753855,Virginia,USA,22 Hours Left
4,27700,Chevrolet,1500,2018,Clean Vehicle,6654,Red,3Gcpcrec2Jg473991,167763266,Florida,USA,22 Hours Left
...,...,...,...,...,...,...,...,...,...,...,...,...
2494,7800,Nissan,Versa,2019,Clean Vehicle,23609,Red,3N1Cn7Ap9Kl880319,167722715,California,USA,1 Days Left
2495,9200,Nissan,Versa,2018,Clean Vehicle,34553,Silver,3N1Cn7Ap5Jl884088,167762225,Florida,USA,21 Hours Left
2496,9200,Nissan,Versa,2018,Clean Vehicle,31594,Silver,3N1Cn7Ap9Jl884191,167762226,Florida,USA,21 Hours Left
2497,9200,Nissan,Versa,2018,Clean Vehicle,32557,Black,3N1Cn7Ap3Jl883263,167762227,Florida,USA,2 Days Left
2498,9200,Nissan,Versa,2018,Clean Vehicle,31371,Silver,3N1Cn7Ap4Jl884311,167762228,Florida,USA,21 Hours Left

In [28]:
#unique values in the condition column
df["condition"].unique()

array(['10 Days Left', '6 Days Left', '2 Days Left', '22 Hours Left',
       '20 Hours Left', '19 Hours Left', '3 Days Left', '21 Hours Left',
       '17 Hours Left', '2 Hours Left', '3 Hours Left', '34 Minutes',
       '16 Hours Left', '18 Hours Left', '1 Days Left', '32 Minutes',
       '14 Hours Left', '5 Hours Left', '4 Days Left', '9 Days Left',
       '23 Hours Left', '8 Days Left', '7 Days Left', '5 Days Left',
       '9 Minutes', '1 Minutes', '7 Hours Left', '16 Minutes',
       '6 Hours Left', '1 Hours Left', 'Listing Expired', '13 Days Left',
       '24 Hours Left', '15 Hours Left', '53 Minutes', '27 Minutes',
       '12 Days Left', '15 Days Left', '30 Minutes', '29 Minutes',
       '28 Minutes', '48 Minutes', '11 Days Left', '4 Hours Left',
       '47 Minutes', '12 Hours Left', '36 Minutes'], dtype=object)

In [29]:
#Function to clean the time_left column w.r.t Days, Hours and Minutes
def extract_time_components(row):
    import re

    # Default values
    days = hours = minutes = 0

    if 'Expired' in row:
        return pd.Series([0, 0, 0])

    # Extract using regex
    day_match = re.search(r'(\d+)\s*Days?', row, re.IGNORECASE)
    hour_match = re.search(r'(\d+)\s*Hours?', row, re.IGNORECASE)
    minute_match = re.search(r'(\d+)\s*Minutes?', row, re.IGNORECASE)

    if day_match:
        days = int(day_match.group(1))
    if hour_match:
        hours = int(hour_match.group(1))
    if minute_match:
        minutes = int(minute_match.group(1))

    return pd.Series([days, hours, minutes])

In [30]:
#Apply to DataFrame
df[['time_left_days', 'time_left_hours', 'time_left_minutes']] = df['condition'].apply(extract_time_components)

In [31]:
#Convert to total hours and minutes
df['total_hours'] = df['time_left_days'] * 24 + df['time_left_hours'] + df['time_left_minutes'] / 60
df['total_minutes'] = df['time_left_days'] * 24 * 60 + df['time_left_hours'] * 60 + df['time_left_minutes']

In [32]:
#Preview of the dataset after cleaning the time_left column
df.head(5)

,price($),brand,model,year,title_status,mileage,color,vin,lot,state,country,condition,time_left_days,time_left_hours,time_left_minutes,total_hours,total_minutes
0,6300,Toyota,Cruiser,2008,Clean Vehicle,274117,Black,Jtezu11F88K007763,159348797,New Jersey,USA,10 Days Left,10,0,0,240.0,14400
1,2899,Ford,Se,2011,Clean Vehicle,190552,Silver,2Fmdk3Gc4Bbb02217,166951262,Tennessee,USA,6 Days Left,6,0,0,144.0,8640
2,5350,Dodge,Mpv,2018,Clean Vehicle,39590,Silver,3C4Pdcgg5Jt346413,167655728,Georgia,USA,2 Days Left,2,0,0,48.0,2880
3,25000,Ford,Doors,2014,Clean Vehicle,64146,Blue,1Ftfw1Et4Efc23745,167753855,Virginia,USA,22 Hours Left,0,22,0,22.0,1320
4,27700,Chevrolet,1500,2018,Clean Vehicle,6654,Red,3Gcpcrec2Jg473991,167763266,Florida,USA,22 Hours Left,0,22,0,22.0,1320

In [33]:
#Drop the repeated and unnecessary columns
df.drop(columns=['condition', 'time_left_days','time_left_hours', 'time_left_minutes','total_minutes'], inplace=True)
df.head(10)

,price($),brand,model,year,title_status,mileage,color,vin,lot,state,country,total_hours
0,6300,Toyota,Cruiser,2008,Clean Vehicle,274117,Black,Jtezu11F88K007763,159348797,New Jersey,USA,240.0
1,2899,Ford,Se,2011,Clean Vehicle,190552,Silver,2Fmdk3Gc4Bbb02217,166951262,Tennessee,USA,144.0
2,5350,Dodge,Mpv,2018,Clean Vehicle,39590,Silver,3C4Pdcgg5Jt346413,167655728,Georgia,USA,48.0
3,25000,Ford,Doors,2014,Clean Vehicle,64146,Blue,1Ftfw1Et4Efc23745,167753855,Virginia,USA,22.0
4,27700,Chevrolet,1500,2018,Clean Vehicle,6654,Red,3Gcpcrec2Jg473991,167763266,Florida,USA,22.0
5,5700,Dodge,Mpv,2018,Clean Vehicle,45561,White,2C4Rdgeg9Jr237989,167655771,Texas,USA,48.0
6,7300,Chevrolet,Pickup,2010,Clean Vehicle,149050,Black,1Gcsksea1Az121133,167753872,Georgia,USA,22.0
7,13350,Gmc,Doors,2017,Clean Vehicle,23525,Gray,1Gks2Gkc3Hr326762,167692494,California,USA,20.0
8,14600,Chevrolet,Malibu,2018,Clean Vehicle,9371,Silver,1G1Zd5St5Jf191860,167763267,Florida,USA,22.0
9,5250,Ford,Mpv,2017,Clean Vehicle,63418,Black,2Fmpk3J92Hbc12542,167656121,Texas,USA,48.0

In [34]:
#Rename the total_hours column to time_left_hours for better understanding
df.rename(columns={'total_hours': 'time_left_hours'}, inplace=True)

In [37]:
#Title case for all columns
df.columns = [col.title() for col in df.columns]
df.head(10)

,Price($),Brand,Model,Year,Title_Status,Mileage,Color,Vin,Lot,State,Country,Time_Left_Hours
0,6300,Toyota,Cruiser,2008,Clean Vehicle,274117,Black,Jtezu11F88K007763,159348797,New Jersey,USA,240.0
1,2899,Ford,Se,2011,Clean Vehicle,190552,Silver,2Fmdk3Gc4Bbb02217,166951262,Tennessee,USA,144.0
2,5350,Dodge,Mpv,2018,Clean Vehicle,39590,Silver,3C4Pdcgg5Jt346413,167655728,Georgia,USA,48.0
3,25000,Ford,Doors,2014,Clean Vehicle,64146,Blue,1Ftfw1Et4Efc23745,167753855,Virginia,USA,22.0
4,27700,Chevrolet,1500,2018,Clean Vehicle,6654,Red,3Gcpcrec2Jg473991,167763266,Florida,USA,22.0
5,5700,Dodge,Mpv,2018,Clean Vehicle,45561,White,2C4Rdgeg9Jr237989,167655771,Texas,USA,48.0
6,7300,Chevrolet,Pickup,2010,Clean Vehicle,149050,Black,1Gcsksea1Az121133,167753872,Georgia,USA,22.0
7,13350,Gmc,Doors,2017,Clean Vehicle,23525,Gray,1Gks2Gkc3Hr326762,167692494,California,USA,20.0
8,14600,Chevrolet,Malibu,2018,Clean Vehicle,9371,Silver,1G1Zd5St5Jf191860,167763267,Florida,USA,22.0
9,5250,Ford,Mpv,2017,Clean Vehicle,63418,Black,2Fmpk3J92Hbc12542,167656121,Texas,USA,48.0

In [38]:
#Statistical summary of the dataset after cleaning
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2476 entries, 0 to 2498
Data columns (total 12 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Price($)         2476 non-null   int64
 1   Brand            2476 non-null   object
 2   Model            2476 non-null   object
 3   Year             2476 non-null   int64
 4   Title_Status     2476 non-null   object
 5   Mileage          2476 non-null   int64
 6   Color            2476 non-null   object
 7   Vin              2476 non-null   object
 8   Lot              2476 non-null   int64
 9   State            2476 non-null   object
 10  Country          2476 non-null   object
 11  Time_Left_Hours  2476 non-null   float64
dtypes: float64(1), int64(4), object(7)
memory usage: 251.5+ KB

In [39]:
#converting df to CSV
df.to_csv('cleaned_usa_cars_dataset.csv', index=False)
print("CSV file saved successfully.")

CSV file saved successfully.